#!/bin/bash

currentBranch=$(git branch --show-current)
readyToPushFiles=$(git diff --name-only origin/$currentBranch...HEAD)

echo "Running spotless check for each file"
allChecksPassed=true
failedFiles=()

for file in $readyToPushFiles; do
    if test -f "$file"; then
        ./gradlew spotlessCheck -Pfile=$file > /dev/null 2>&1

        if [ $? -ne 0 ]; then
            failedFiles+=("$file")
            allChecksPassed=false
        else
            git add $file
        fi
    fi
done

if [ "$allChecksPassed" = false ]; then
    echo "❌ Spotless check failed for the following files:" >&2
    for file in "${failedFiles[@]}"; do
        echo "  - $file" >&2
    done
    exit 1
fi

echo "✅ spotless check succeed for all files"